languageCode = "en-us"
title = "Prologue"
baseurl = "http://www.menaru.com/"
theme = "prologue"

[params]
  name = "Mena (Meng) Ru"
  description = "Through the Looking Glass"
  copyright = "Untitled."

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "instagram.com/menaruphoto"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "menaru13@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = ""
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = ""
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = ""
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = ""
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = ""
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = ""
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
